name: mettransformer
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - math
  - random
  - warnings
  - copy
  - torch
  - torch.nn
  - partial
  - python=3.9
  - pytables
  - uproot
  - pandas
  - h5py
  - tqdm
  - weaver
  - scikit-learn
  - autopep8
  - pip
  - pip:
    - setGPU
    - mplhep
    - git+https://github.com/google/qkeras#egg=qkeras
    - git+https://github.com/jmduarte/hls4ml@l1metml#egg=hls4ml[profiling]
